// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPkaNavJh-8esfntJ3YjlhCbAl0XoLP8',
    appId: '1:715682825895:web:09dae7d27afafa224cbd82',
    messagingSenderId: '715682825895',
    projectId: 'proyecto-moviles-b3aea',
    authDomain: 'proyecto-moviles-b3aea.firebaseapp.com',
    storageBucket: 'proyecto-moviles-b3aea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJNMYcDIr0H39QWuai8uP_WJtPkvVJ5g',
    appId: '1:715682825895:android:90c9d811d08cd96a4cbd82',
    messagingSenderId: '715682825895',
    projectId: 'proyecto-moviles-b3aea',
    storageBucket: 'proyecto-moviles-b3aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnX07qv1cvxXRW002z6LAlW9lXP-xoNcA',
    appId: '1:715682825895:ios:f406b22f9b0bae544cbd82',
    messagingSenderId: '715682825895',
    projectId: 'proyecto-moviles-b3aea',
    storageBucket: 'proyecto-moviles-b3aea.appspot.com',
    iosBundleId: 'com.example.proyecto1',
  );

}